-- ========================================
-- Migration: Update RooftopKC Tables
-- Created: 2026-04-23
-- Description: Update seating capacity for existing RooftopKC tables (1-17)
--              and add 7 new tables (18-24) to support expanded capacity
--
-- Tables Affected: tables
-- Dependencies: 20260413000000_create_locations_table.sql, 20260413000001_add_location_id_to_tables.sql
-- Breaking Changes: NO - Only updates seat counts and adds new tables
-- ========================================

-- ========================================
-- STEP 1: UPDATE EXISTING TABLE CAPACITIES
-- ========================================

DO $$
DECLARE
  rooftop_location_id UUID;
BEGIN
  -- Get RooftopKC location ID
  SELECT id INTO rooftop_location_id
  FROM public.locations
  WHERE slug = 'rooftopkc';

  IF rooftop_location_id IS NULL THEN
    RAISE EXCEPTION 'RooftopKC location not found. Ensure locations table is seeded.';
  END IF;

  -- Update existing tables 1-17 with new seating capacities
  -- Tables 1-9: 2 seats each
  UPDATE public.tables
  SET seats = 2, updated_at = NOW()
  WHERE location_id = rooftop_location_id AND table_number = 1;

  UPDATE public.tables
  SET seats = 2, updated_at = NOW()
  WHERE location_id = rooftop_location_id AND table_number = 2;

  UPDATE public.tables
  SET seats = 2, updated_at = NOW()
  WHERE location_id = rooftop_location_id AND table_number = 3;

  UPDATE public.tables
  SET seats = 2, updated_at = NOW()
  WHERE location_id = rooftop_location_id AND table_number = 4;

  UPDATE public.tables
  SET seats = 2, updated_at = NOW()
  WHERE location_id = rooftop_location_id AND table_number = 5;

  UPDATE public.tables
  SET seats = 2, updated_at = NOW()
  WHERE location_id = rooftop_location_id AND table_number = 6;

  UPDATE public.tables
  SET seats = 2, updated_at = NOW()
  WHERE location_id = rooftop_location_id AND table_number = 7;

  UPDATE public.tables
  SET seats = 2, updated_at = NOW()
  WHERE location_id = rooftop_location_id AND table_number = 8;

  UPDATE public.tables
  SET seats = 2, updated_at = NOW()
  WHERE location_id = rooftop_location_id AND table_number = 9;

  -- Table 10: 6 seats
  UPDATE public.tables
  SET seats = 6, updated_at = NOW()
  WHERE location_id = rooftop_location_id AND table_number = 10;

  -- Tables 11-12: 4 seats each
  UPDATE public.tables
  SET seats = 4, updated_at = NOW()
  WHERE location_id = rooftop_location_id AND table_number = 11;

  UPDATE public.tables
  SET seats = 4, updated_at = NOW()
  WHERE location_id = rooftop_location_id AND table_number = 12;

  -- Tables 13-14: 6 seats each
  UPDATE public.tables
  SET seats = 6, updated_at = NOW()
  WHERE location_id = rooftop_location_id AND table_number = 13;

  UPDATE public.tables
  SET seats = 6, updated_at = NOW()
  WHERE location_id = rooftop_location_id AND table_number = 14;

  -- Tables 15-16: 4 seats each
  UPDATE public.tables
  SET seats = 4, updated_at = NOW()
  WHERE location_id = rooftop_location_id AND table_number = 15;

  UPDATE public.tables
  SET seats = 4, updated_at = NOW()
  WHERE location_id = rooftop_location_id AND table_number = 16;

  -- Table 17: 10 seats
  UPDATE public.tables
  SET seats = 10, updated_at = NOW()
  WHERE location_id = rooftop_location_id AND table_number = 17;

  RAISE NOTICE 'Updated seating capacity for RooftopKC tables 1-17';

END $$;

-- ========================================
-- STEP 2: INSERT NEW TABLES 18-24
-- ========================================

DO $$
DECLARE
  rooftop_location_id UUID;
BEGIN
  -- Get RooftopKC location ID
  SELECT id INTO rooftop_location_id
  FROM public.locations
  WHERE slug = 'rooftopkc';

  -- Insert new tables 18-24
  -- Note: id is auto-generated by trigger, created_at/updated_at have defaults
  INSERT INTO public.tables (table_number, location_id, seats)
  VALUES
    (18, rooftop_location_id, 2),
    (19, rooftop_location_id, 4),
    (20, rooftop_location_id, 4),
    (21, rooftop_location_id, 6),
    (22, rooftop_location_id, 4),
    (23, rooftop_location_id, 2),
    (24, rooftop_location_id, 4)
  ON CONFLICT (location_id, table_number) DO UPDATE
    SET seats = EXCLUDED.seats,
        updated_at = NOW();

  RAISE NOTICE 'Inserted new RooftopKC tables 18-24';

END $$;

-- ========================================
-- MIGRATION COMPLETE - VERIFICATION
-- ========================================

-- Verify RooftopKC now has 24 tables with correct capacities
SELECT
    t.table_number,
    t.seats,
    l.name as location_name,
    l.slug as location_slug
FROM public.tables t
JOIN public.locations l ON t.location_id = l.id
WHERE l.slug = 'rooftopkc'
ORDER BY t.table_number;

-- Summary: Total tables and seats per location
SELECT
    l.name as location_name,
    l.slug as location_slug,
    COUNT(t.id) as table_count,
    SUM(t.seats) as total_seats
FROM public.locations l
LEFT JOIN public.tables t ON t.location_id = l.id
GROUP BY l.name, l.slug
ORDER BY l.name;

-- Expected results:
-- RooftopKC: 24 tables, 88 total seats
-- Noir KC: 20 tables (unchanged)
