name: Process Reservation Reminders

on:
  schedule:
    - cron: '*/1 * * * *'  # Every 1 minutes
  workflow_dispatch:

jobs:
  process-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Call webhook
        run: |
          curl -X POST "https://noir-crm-dashboard.vercel.app/api/webhook-process-reminders" \
            -H "Content-Type: application/json" \
            -H "x-webhook-secret: ${{ secrets.WEBHOOK_SECRET }}"
