name: Process Reservation Reminders

on:
  schedule:
    - cron: '*/1 * * * *'  # Every minute
  workflow_dispatch:  # Allow manual trigger

jobs:
  process-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Call webhook
        run: |
          curl -X POST "https://noir-crm-dashboard-hw7jln68k-qesmseps-projects.vercel.app/api/webhook-process-reminders" \
            -H "x-webhook-secret: ${{ secrets.WEBHOOK_SECRET }}" \
            -H "Content-Type: application/json" 